# Generated by Django 4.0.5 on 2022-07-21 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_post_add_date_post_author_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='add_date',
        ),
    ]
