# Generated by Django 4.0.5 on 2022-07-21 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_remove_post_add_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
