# Generated by Django 4.0.5 on 2022-07-21 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_remove_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
