# Generated by Django 4.0.5 on 2022-07-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_post_author_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=500),
        ),
    ]
